### ISSUE TITLE
HEX files

### ISSUE THREAD

**Issue by iw0red** [pttlink/voter#1]
Hi everyone,
I'm looking for the hex files for the voter board. Where I can find it?
Thanks in advance.
73 Marco IW0RED.

**Comment by ccie2285** [comment]
https://github.com/AllStarLink/voter/tree/master/board-firmware

There are several .cry files.  Just find the one that you want.  
SMT is for the surface mount RTCM.
Those without SMT are for the hand built voter board.  
There are several different options that were used for compiling and those are indicated by other parts of the file names.

**Comment by iw0red** [comment]
Thanks.
I don't have any experience with pic programming. I have build the voter board like this https://allstarlink.org/voterr-reva.jpg and now I need to programming the pic.
Which is the simplest way?
73 Marco IW0RED

**Comment by KG7QIN** [comment]
First files in the repo seem like they used something called an EBLEX C30 programmer.  My guess is something like that.  I'd ask on app_rpt to see what comes up since it is related in a bit.

**Comment by N4IRS** [comment]
This may help.
https://wiki.allstarlink.org/wiki/RTCM_Client

73, Steve N4IRS

**Comment by iw0red** [comment]
Thanks, everyone for the help.
I'll make some tests.
73 Marco IW0RED.
